travis:
  secure:
    BINSTAR_TOKEN: k+qoT5B0uIG9iSPwAN+jrB2qWXzhZLUjUcxzjcWQqDVQ8BlS5btz17I3+EDMDcX8wfIJxNDj56KwR/JxGD04Z+eiypvqHTs39mBNiqCa75K/ktL5gMp41i8AJeWh5PEfFktzsnT8Hroi6t6UFb0nzMwWQSeJHSfl2n+xNweanTnM5f3yJtnFCn/39MgVI/RQpQlvopg328qWY5j69v+/xgWUTUJpQVjuZVP+cgrmB41ALj4NVNI5gbamzE7kmVR7fTTGpMJGHVutnNqE6Gb6Ml4H0n4bwsGpKn/nj2HlgGrFEDmz6RNIvM7s66D9EfJ2ubCQ6JdJPuJ7HHyB3IjJM/fnQ4QlsCWe7Q0tmAL2sy7+nf+8UuYX/tvzmFE8O66H/pI9RuqlFkgxlvtfdaCvOsUn3rbfewblt6SNVIpzx+KZUpf1JDLANVqi3GjKZ+UZV0TXBRiwqavRC8CqXhN0Tt9SbrKEyFYWVPf0pFsMfZ7uwU74W7LR1qsrPFbmMfmjRGsJZeomb2a/+TUCBS7xr7SgPQ5IQa9Q5b5DMfy+dlfZELhLcKwd2VMcwe7j+FajIkz7xw45XcHVJpz/Tg0CBOWk2WAMjDIIBdzbgrSc2wTh6ufYf8JTt46ul3eeRuynxNQFkxsrk+4V8L+4juTWxy6DyIdFzlJly/Kj9FO0sgM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
